# Filename:       docker-compose.yml
# Author:         Andy Horn
# Created:        4/10/2020
# Description:    This is the base/production version of the 
#                 docker-compose configuration for the app.
#                 It will launch all the containers in "production" mode.

version: "3"
services:
  # Vue.js frontend
  web:
    container_name: rg-web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: "production"
    ports:
      - ${WEB_PORT:-80:80} # Pull the web port from the environment - default to 80
    restart: "unless-stopped"

  # PostgreSQL Database
  database:
    container_name: "database"
    image: postgres:12
    restart: unless-stopped
    env_file: 
      - database.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # PGAdmin Server
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:4
    restart: unless-stopped
    env_file: 
      - pgadmin.env
    ports:
      - "8080:80"

# Save database data
volumes:
  db_data: