# Filename:     docker-compose.dev.yml
# Author:       Andy Horn
# Created:      6/8/2020
# Description:  This is a Development-mode docker-compose file that will
#               launch the databases and a PGAdmin container, the DotNet Core
#               API will need to be launched manually, along with the Vue.js server.

version: "3"
services:
  database:
    container_name: rg-database
    image: mongo
    env_file: .env
    ports:
      - "27017-27019:27017-27019"

  identity:
    container_name: rg-identity
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "8000:80"
    depends_on:
      - identity
