# Filename:     docker-compose.dev.yml
# Author:       Andy Horn
# Created:      4/12/2020
# Description:  This is a Development-mode override file that will change
#               configuration settings to put the applications into 
#               "development" mode instead of "production" mode.

version: "3"
services:
  web:
    build:
      # Use the development-spec Dockerfile
      context: ./web
      dockerfile: Dockerfile.dev
    environment: 
      # Set the node environment to "development"
      NODE_ENV: "development"
    volumes:
      # Mount the local files to the container
      - ./web/src:/app/src

  api:
    ports:
      # Expose the port externally during development for testing
      - "5000:5000"
    environment:
      # Set the environment to "Development" instead of "Production"
      ASPNETCORE_ENVIRONMENT: Development

  database:
    ports:
      - "27017-27019:27017-27019"

  identity:
    ports:
      - "5432:5432"