### DEVELOPMENT MODE ###
########################

# Pull the Node.js alpine-linux image
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy the project package file
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the application files
COPY . .

# Run the development server
ENTRYPOINT [ "npm", "run", "serve" ]